# Generated by Django 5.0.2 on 2024-03-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_editora_url_editora_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="editora",
            old_name="site",
            new_name="url",
        ),
    ]
