# Generated by Django 5.0.2 on 2024-08-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_editora_cidade_editora_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
