# Generated by Django 5.0.2 on 2024-08-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_autor_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor",
            new_name="autores",
        ),
    ]
